### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by himsen** [open-quantum-safe/openssh-portable#18]
I see several compiler warnings when doing a standard build on an Ubuntu 14.04 box.

E.g.

```
kexhyecdhoqsc.c:145:14: warning: variable ‘kex’ set but not used [-Wunused-but-set-variable]
  struct kex *kex = NULL;
              ^
kexpqoqsc.c:196:14: warning: variable ‘kex’ set but not used [-Wunused-but-set-variable]
  struct kex *kex = NULL;
              ^
kexpqoqsc.c: In function ‘pq_oqs_client’:
kexoqs.c:286:1: warning: label ‘out’ defined but not used [-Wunused-label]
 out:
 ^
kexhyecdhoqsc.c: In function ‘input_hybrid_ecdh_oqs_reply’:
kexhyecdhoqsc.c:328:3: warning: implicit declaration of function ‘memcpy’ [-Wimplicit-function-declaration]
   memcpy(kex->session_id, hash, kex->session_id_len);
   ^
kexhyecdhoqsc.c:328:3: warning: incompatible implicit declaration of built-in function ‘memcpy’ [enabled by default]
kexpqoqsc.c:276:3: warning: passing argument 1 of ‘pq_oqs_free’ from incompatible pointer type [enabled by default]
   pq_oqs_free(oqs_kex_ctx);
```

Should be quick to solve by adding missing includes and remove unused variables.
